# FROM defines the base image
FROM tensorflow/tensorflow:2.1.0-gpu-py3 

# set the working directory 
WORKDIR /home/ubuntu/tf2_sac

# pass the repo file
COPY . .

RUN apt -y update
RUN apt install -y libopenmpi-dev
RUN apt install -y vim

# install pip packages
RUN pip install --upgrade pip
RUN pip install -r docker/requirements.txt

# CMD defines the default command to be run in the container 
# CMD is overridden by supplying a command + arguments to 
# `docker run`, e.g. `nvcc --version` or `bash`
CMD bash
