# FROM defines the base image
FROM tensorflow/tensorflow:devel-py3 

# set the working directory 
WORKDIR /home/ubuntu/docker_demo

# pass the repo file
COPY . .

RUN apt -y update
RUN apt install -y git
RUN apt install -y libopenmpi-dev
RUN apt install -y xvfb
RUN apt install -y python-opengl
RUN apt install -y fontconfig
RUN apt install -y vim

# install pip packages
RUN pip install --upgrade pip
RUN pip install -r docker/requirements.txt

# CMD defines the default command to be run in the container 
# CMD is overridden by supplying a command + arguments to 
# `docker run`, e.g. `nvcc --version` or `bash`
CMD bash
